### ISSUE TITLE
wrong file extension

### ISSUE THREAD

**Issue by mbannert** [h4sci/tasks-queens#1]
Just spotted a wrong file extension. Probably just a typo, but might cause trouble later on. 
Can you fix this @Vilenaria?  
Should by `intro-survey.csv`, not CVS. csv =  CommaSeparatedValue

**Comment by JanicBucheli** [comment]
I just assigned myself for this task and uploaded the correct file. I guess the others have to pull the repository to get the latest files?

**Comment by mbannert** [comment]
right @JanicBucheli . You don't sync anything with them automatically. They have to pull. Corrections like this are a perfect exercise of how to update etc.
